**Scikitlearn workflow**

In [2]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

scikitlearn workflow

In [3]:
#getting the data ready
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
#creates features and labels
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

In [5]:
#Choosing the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=200 )
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
#Fit the model to training data or split into train and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [6]:
clf.fit(X_train,y_train);
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
84    42    0   0       102   265    0        0      122      0      0.6   
158   58    1   1       125   220    0        1      144      0      0.4   
120   64    0   0       130   303    0        1      122      0      2.0   
301   57    1   0       130   131    0        1      115      1      1.2   
197   67    1   0       125   254    1        1      163      0      0.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
83    52    1   3       152   298    1        1      178      0      1.2   
47    47    1   2       138   257    0        0      156      0      0.0   
87    46    1   1       101   197    1        1      156      0      0.0   
88    54    0   2       110   214    0        1      158      0      1.6   
123   54    0   2       108   267    0        0      167      0      0.0   

     slope  ca  thal  
84       1   0     2  
158      1   4     3  
120      1   2     2  
301      1   1     3  
197      1   2     3  
..     ...  ..   ...  
83       1   0     3  
47       2   0     2  
87       2   0     3  
88       1   0     2  
123      2   0     2  

[242 rows x 13 columns]

In [7]:
#Make prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1])

In [8]:
#Check accuracy
clf.score(X_train,y_train)

1.0

In [9]:
clf.score(X_test,y_test)

0.819672131147541

In [10]:
#metrics
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.87      0.79      0.83        34
           1       0.77      0.85      0.81        27

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [11]:
#improving a model
np.random.seed(42)
for i in range(10,100,10):
  print(f"Trying model with {i} estimators....")
  clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
  print(f"Model accuracy on test set: {clf.score(X_test,y_test) * 100}% ")


Trying model with 10 estimators....
Model accuracy on test set: 77.04918032786885% 
Trying model with 20 estimators....
Model accuracy on test set: 80.32786885245902% 
Trying model with 30 estimators....
Model accuracy on test set: 80.32786885245902% 
Trying model with 40 estimators....
Model accuracy on test set: 78.68852459016394% 
Trying model with 50 estimators....
Model accuracy on test set: 78.68852459016394% 
Trying model with 60 estimators....
Model accuracy on test set: 83.60655737704919% 
Trying model with 70 estimators....
Model accuracy on test set: 80.32786885245902% 
Trying model with 80 estimators....
Model accuracy on test set: 81.9672131147541% 
Trying model with 90 estimators....
Model accuracy on test set: 77.04918032786885% 


**Getting Our Data Ready**

* Split the data into features and labels or disregarding missing values,Usually in X and y.

* Filling missing values is also known as imputing;

* Converting non numeric data to numeric is also known as feature encoding!

In [12]:
  heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [13]:
#Features
X = heart_disease.drop("target",axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [14]:
#labels
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [15]:
#Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

Make sure the data is in numerical

In [16]:
car_sales = pd.read_csv("/content/drive/MyDrive/car-sales-extended.csv")
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [17]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [18]:
#Split into features and labels
X = car_sales.drop("Price",axis=1)
y = car_sales["Price"]

In [19]:
#Train and test splits
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [20]:
#Choose machine learning model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [ ]:
#1.featutre encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

#2.define categorical columns to transform
categorical_features = ["Make","Colour","Doors"]

#3.Create an instance of OneHotEncoder
one_hot = OneHotEncoder()

#4.Create an instance Of ColumnTransformer
transformer = ColumnTransformer([("one_hot", one_hot , categorical_features)],remainder="passthrough")

#5.Turn categorical features into numbers
transformed_X = transformer.fit_transform(X);
transformed_X

**What if missing values**

In [ ]:
import pandas as pd

In [ ]:
car_sales_missing = pd.read_csv("/content/drive/MyDrive/car-sales-extended-missing-data.csv")
car_sales_missing

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
#dropna
car_sales_missing.dropna(subset=["Price"],inplace=True)

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
car_sales_missing["Doors"].value_counts()

In [ ]:
#Split into x and y
X = car_sales_missing.drop("Price",axis=1)
y = car_sales_missing["Price"]

#split into train and test splits
import numpy as np
np.random.seed(42)
from sklearn.model_selection import train_test_split
X_train,y_train,X_test,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
#check missing values
X.isna().sum() , y.isna().sum()

In [ ]:
#filling missing values with scikitlearn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#filling categorical columns as "missing" and numers as mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#define columns
cat_features = ["Make", "Colour"]
door_feature = ["Doors"]
num_feature = ["Odometer (KM)"]

#create an imputer that fills missing values
imputer = ColumnTransformer([("cat_imputer",cat_imputer,cat_features),
                   ("door_imputer",door_imputer,door_feature),
                   ("num_imputer",num_imputer,num_feature )])


#fill trainvalues
imputer.fit_transform(X)

**SkLearn Map**

In [ ]:
#boston house data
import pandas as pd
boston = pd.read_csv("/submission_example.csv")
boston

In [ ]:
len(boston)

In [ ]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit()
reg.coef_ ``````````````

**Picking a machine learning model for our classification problem**

In [22]:
heart_disease = pd.read_csv("/content/drive/MyDrive/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [23]:
#check how many samples
len(heart_disease)

303

In [24]:
#creates features and labels
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

In [25]:
#Choosing the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

In [26]:
#Fit the model to training data or split into train and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [27]:
#fit the data
clf.fit(X_train,y_train);
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
272   67    1   0       120   237    0        1       71      0      1.0   
64    58    1   2       140   211    1        0      165      0      0.0   
282   59    1   2       126   218    1        1      134      0      2.2   
259   38    1   3       120   231    0        1      182      1      3.8   
240   70    1   2       160   269    0        1      112      1      2.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
58    34    1   3       118   182    0        0      174      0      0.0   
91    57    1   0       132   207    0        1      168      1      0.0   
167   62    0   0       140   268    0        0      160      0      3.6   
146   44    0   2       118   242    0        1      149      0      0.3   
215   43    0   0       132   341    1        0      136      1      3.0   

     slope  ca  thal  
272      1   0     2  
64       2   0     2  
282      1   1     1  
259      1   0     3  
240      1   1     3  
..     ...  ..   ...  
58       2   0     2  
91       2   0     3  
167      0   2     2  
146      1   1     2  
215      1   0     3  

[242 rows x 13 columns]

In [28]:
y_test

42     1
291    0
15     1
51     1
265    0
      ..
18     1
247    0
126    1
131    1
176    0
Name: target, Length: 61, dtype: int64

In [29]:
#Make prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

* If the percentage above 70 percentage then the machine learning model wotrks well.

In [30]:
#Check accuracy
clf.score(X_train,y_train)

1.0

In [31]:
clf.score(X_test,y_test)

0.7704918032786885

**Making predictions using machinelearning model**

* `Predict` predicts the given model!
* `Predict proba` returns the propabilities of given truth labels.

In [32]:
#Make prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [33]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_preds,y_test)

0.7704918032786885

In [ ]:
clf.predict_proba(X_test)

**Saving a model**

In [21]:
import pickle

In [34]:
pickle.dump(clf,open("heart_disease_classifier.pkl","wb"))

In [36]:
#loading a machine learning model
loaded_model = pickle.load(open("/content/heart_disease_classifier.pkl","rb"))

In [37]:
#make predictions using loaded model
loaded_model.predict(X_test)

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

**Scikitlearn end **