In [31]:
#Import numpy
import numpy as np

**Datatypes and Attributes**

In [32]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [33]:
type(a1)

numpy.ndarray

In [34]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1.shape

(4,)

In [37]:
a2.shape

(2, 3)

In [38]:
a3.shape

(2, 3, 3)

In [39]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [40]:
a1.dtype,  a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [41]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [42]:
#Creating datatrame u7sing pandas
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

**Creating Arrays**

In [43]:
#Creating a simple array
simple_array = np.array([1,2,3])
simple_array

array([1, 2, 3])

In [44]:
simple_array.dtype

dtype('int32')

In [45]:
#Creating arrays with ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
#EBy default it creates float(np.ones)
ones.dtype

dtype('float64')

In [47]:
#astype
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [48]:
ones.dtype

dtype('float64')

In [49]:
#Create an arrays of zeros
zeros = np.zeros((5,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
#Create an array with range of values
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [51]:
#Creating an random array
random_array = np.random.randint(10,size=(5,3))
random_array

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [52]:
#Creates a random floats between 0 and 1
random_float = np.random.random((5,3))
random_float

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ]])

In [53]:
#Numpy seed
np.random.seed(0)
#Creating an random array
random_array = np.random.randint(10,size=(5,3))
random_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

**Viewing Arrays and Matrices**

In [54]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a1

array([1, 2, 3, 4])

In [56]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a1[0]

1

In [59]:
a2.shape

(2, 3)

In [60]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a2[0]

array([1, 2, 3])

In [62]:
a3.shape

(2, 3, 3)

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [65]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [66]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [67]:
#Get first four numbers in the innermost array
a4[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

**Manipulating And Comparing Arrays**

In [68]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [69]:
ones =  np.ones(3)
ones

array([1., 1., 1.])

In [70]:
a1 + ones

array([2., 3., 4.])

In [71]:
a1 - ones

array([0., 1., 2.])

In [72]:
a1 * ones

array([1., 2., 3.])

In [77]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [79]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [ ]:
a1 / ones

array([1., 2., 3.])

In [ ]:
#Floor Division
a1 // a2

array([[1, 1, 1],
       [0, 0, 0]])

In [ ]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
a1 % a2

array([[0, 0, 0],
       [1, 2, 3]])

Aggregation - performing same operation on number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

list

In [ ]:
sum(listy_list)

6

In [ ]:
sum(a1)

6

In [ ]:
np.sum(a1)

6

In [ ]:
#Create a massive numpy array
massive_array = np.random.random(1000000)
massive_array.size

1000000

In [ ]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [ ]:
%timeit sum(massive_array) #python way of summing
%timeit np.sum(massive_array) #numpy way of summing

119 ms ± 26.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
395 µs ± 9.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
np.mean(a2)

3.5

In [ ]:
np.max(a2)

6

In [ ]:
np.min(a2)

1

In [ ]:
#Standarad deviation and variance is the measure of spread of data
np.std(a2)

1.707825127659933

In [ ]:
np.var(a2)

2.9166666666666665

In [ ]:
#Standard deviation = is the squareroot of variance
np.sqrt(np.var(a2))

1.707825127659933

**Reshaping, Transpose and Dotproduct**

In [ ]:
#Reshaping
a1

array([1, 2, 3])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [ ]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2.reshape(2,3,1) + a3

array([[[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]],

       [[14, 15, 16],
        [18, 19, 20],
        [22, 23, 24]]])

In [ ]:
#Transpose -> Reverses the order of axis
# For example (2,3), -> (3,2)
a2.shape

(2, 3)

In [ ]:
a2.T.shape

(3, 2)

In [ ]:
a2.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#For larger arrays , the default value of transpose is to swap the first and last axes
#For example (5,3,3) -> (3,3,5)
matrix = np.random.random(size=(5,3,3))
matrix

array([[[0.14654502, 0.60635704, 0.07089682],
        [0.70310268, 0.05444735, 0.70522489],
        [0.24913388, 0.18467829, 0.27200768]],

       [[0.09627673, 0.75047279, 0.95709062],
        [0.99471268, 0.31927684, 0.69772732],
        [0.07890611, 0.1051645 , 0.86010348]],

       [[0.45700263, 0.02583531, 0.88255474],
        [0.82233356, 0.091974  , 0.70147352],
        [0.0606665 , 0.71862918, 0.26815019]],

       [[0.81378364, 0.38773009, 0.00314084],
        [0.12410789, 0.40712344, 0.46278784],
        [0.93896815, 0.48335273, 0.72745962]],

       [[0.93088285, 0.69488751, 0.65228839],
        [0.02473018, 0.11423181, 0.20469086],
        [0.75407151, 0.77238991, 0.34986169]]])

In [ ]:
matrix.shape

(5, 3, 3)

In [ ]:
matrix.T

array([[[0.14654502, 0.09627673, 0.45700263, 0.81378364, 0.93088285],
        [0.70310268, 0.99471268, 0.82233356, 0.12410789, 0.02473018],
        [0.24913388, 0.07890611, 0.0606665 , 0.93896815, 0.75407151]],

       [[0.60635704, 0.75047279, 0.02583531, 0.38773009, 0.69488751],
        [0.05444735, 0.31927684, 0.091974  , 0.40712344, 0.11423181],
        [0.18467829, 0.1051645 , 0.71862918, 0.48335273, 0.77238991]],

       [[0.07089682, 0.95709062, 0.88255474, 0.00314084, 0.65228839],
        [0.70522489, 0.69772732, 0.70147352, 0.46278784, 0.20469086],
        [0.27200768, 0.86010348, 0.26815019, 0.72745962, 0.34986169]]])

In [ ]:
matrix.T.shape

(3, 3, 5)

In [ ]:
#Dot product
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [ ]:
#Element wise multiplicatiopn
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
#Transpose mat2
mat2.T.shape

(3, 5)

In [ ]:
#Dotproduct
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

**Dot Product Example(Nut Butter Sales**

In [ ]:
np.random.seed(0)
#No of jars sold
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
#Create a weekly salres Dataframe
weekly_sales = pd.DataFrame(sales_amount,index=["Mon","Tue","Thurs","Fri","Sat"],
                            columns=["AlmondButter","CashewButter","PeanutButter"])
weekly_sales

AlmondButter  CashewButter  PeanutButter
Mon              12            15             0
Tue               3             3             7
Thurs             9            19            18
Fri               4             6            12
Sat               1             6             7

In [ ]:
#Create a price array
prices = np.array([10,18,13])
prices

array([10, 18, 13])

In [ ]:
prices.shape

(3,)

In [ ]:
#Create biutter prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["AlmondButter","CashewButter","PeanutButter"])
butter_prices

AlmondButter  CashewButter  PeanutButter
Price            10            18            13

In [ ]:
prices.shape

(3,)

In [ ]:
sales_amount.shape

(5, 3)

In [ ]:
total_sales = prices.dot(sales_amount)
total_sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [ ]:
#Let's Transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([390, 175, 666, 304, 209])

In [ ]:
weekly_sales["Total Sales"] = total_sales

In [ ]:
weekly_sales

AlmondButter  CashewButter  PeanutButter  Total Sales
Mon              12            15             0          390
Tue               3             3             7          175
Thurs             9            19            18          666
Fri               4             6            12          304
Sat               1             6             7          209

**Comparision Operators**

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a1 > 5


array([False, False, False])

In [ ]:
a1 < 5

array([ True,  True,  True])

In [ ]:
a1 == a1

array([ True,  True,  True])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

**Sorting Arrays**

In [ ]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
random_array.shape

(3, 5)

In [ ]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [ ]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
np.argsort(a1)

array([0, 1, 2])

In [ ]:
np.argmin(a1)

0

In [ ]:
np.argmax(a1)

2

**Numpy images**

In [ ]:
#Turn images into numpy array
from matplotlib.image import imread
malvikasharma = imread("/content/download.jpg")
type(malvikasharma)

numpy.ndarray

In [ ]:
malvikasharma.size, malvikasharma.shape, malvikasharma.ndim

(150975, (275, 183, 3), 3)

In [ ]:
malvikasharma[:5]

array([[[ 36,  69, 112],
        [ 36,  69, 112],
        [ 38,  69, 113],
        ...,
        [ 13,  27,  30],
        [ 27,  40,  49],
        [ 25,  36,  54]],

       [[ 45,  76, 120],
        [ 46,  77, 121],
        [ 46,  77, 121],
        ...,
        [ 50,  63,  69],
        [ 67,  79,  91],
        [ 49,  60,  80]],

       [[ 57,  86, 130],
        [ 57,  86, 130],
        [ 58,  87, 131],
        ...,
        [132, 145, 154],
        [113, 125, 141],
        [ 64,  74,  99]],

       [[ 62,  89, 134],
        [ 62,  89, 134],
        [ 65,  89, 135],
        ...,
        [ 20,  32,  48],
        [ 26,  37,  59],
        [ 27,  36,  65]],

       [[ 61,  84, 128],
        [ 62,  85, 129],
        [ 62,  85, 129],
        ...,
        [ 63,  74,  96],
        [ 54,  63,  92],
        [ 29,  38,  71]]], dtype=uint8)